name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test and Generate coverage report (ubuntu and mac)
      if: matrix.os != windows-latest
      run: |
        go mod tidy
        go test -short -coverprofile=coverage.out -covermode=atomic .
        
    - name: Test only (Windows)
      if: matrix.os == windows-latest
      run: |
        go mod tidy
        go test -short .
        
    - name: Upload coverage to Codecov (ubuntu and mac)
      if: matrix.os != windows-latest
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        env_vars: ${{ matrix.os }},GO
#         name: codecov-umbrella
#         path_to_write_report: ./coverage/codecov_report.gz
